name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  flake-check:
    name: Flake check
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          backtrace: full
          logger: pretty
          kvm: false

      - name: Check Nix flake for errors
        run: nix flake check
