name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  flake:
    name: Flake
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          backtrace: full
          logger: pretty
          kvm: false

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix flake lockfile
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
          send-statistics: false

      - name: Check Nix flake for errors
        run: nix flake check
